---
- name: Installer MariaDB
  ansible.builtin.yum:
    name: mariadb-server
    state: present
  become: true

- name: Démarrer et activer MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Sécuriser l'installation de MariaDB
  ansible.builtin.command: mysql_secure_installation
  become: true

- name: Créer une base de données
  mysql_db:
    name: testdb
    state: present
  become: true

- name: Créer un utilisateur et lui accorder des privilèges
  mysql_user:
    name: testuser
    password: testpassword
    priv: 'testdb.*:ALL'
    state: present
  become: true
